# GitHub Actions로 Notion → GitHub Pages 자동 동기화
# 10분마다 자동으로 실행되며, 이미지 포함 완전 자동화

name: Notion to GitHub Blog

on:
  # 10분마다 자동 실행
  schedule:
    - cron: '*/10 * * * *'
  
  # 수동 실행도 가능
  workflow_dispatch:

# GitHub Actions에 쓰기 권한 부여
permissions:
  contents: write

jobs:
  sync-notion-to-blog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install @notionhq/client@2.2.15
          npm install axios@1.6.2
      
      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.NOTION_TOKEN }}" ]; then
            echo "❌ NOTION_TOKEN이 설정되지 않았습니다!"
            exit 1
          fi
          if [ -z "${{ secrets.NOTION_DATABASE_ID }}" ]; then
            echo "❌ NOTION_DATABASE_ID가 설정되지 않았습니다!"
            exit 1
          fi
          echo "✅ Secrets 확인 완료"
          echo "NOTION_TOKEN: ${NOTION_TOKEN:0:10}..."
          echo "NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}"
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      
      - name: Sync Notion to Blog
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node .github/scripts/notion-sync.js
      
      - name: Commit and Push
        run: |
          # Git 설정
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 먼저 모든 untracked/unstaged 파일 stash
          git add -A
          git stash --include-untracked || echo "Nothing to stash"
          
          # 이제 _posts와 images만 다시 추가
          git stash pop || echo "Nothing to pop"
          git reset
          git add _posts/ images/ 2>/dev/null || true
          
          # 변경사항 확인
          if git diff --staged --quiet; then
            echo "✅ 변경사항 없음 - Notion에 '업로드 준비' 상태인 글이 없습니다"
            exit 0
          fi
          
          echo "✅ 변경사항 발견 - 커밋 진행"
          
          # 원격에서 최신 변경사항 가져오기
          git fetch origin master
          git rebase origin/master
          
          # 커밋
          git commit -m "Auto-sync from Notion [skip ci]"
          
          # 푸시
          git push origin master
          
          echo "✅ Push 성공!"
